"""Phase 5 — ``hea.compare`` integration for ``glm``.

Pins ``anova(glm1, glm2[, ...])`` against the ``anova.glm()`` oracles
generated by ``tests/scripts/make_glm_oracles.R``. Test selection mirrors R's
defaults: scale-known families (Poisson/Binomial) → Chisq LRT;
unknown-scale families (Gaussian/Gamma/IG) → F-test using the largest
model's Pearson dispersion as denominator.

``AIC()`` / ``BIC()`` already accept anything with ``.AIC``/``.BIC``/
``.npar``; we just smoke-test that they don't blow up on a glm fit and
that the printed ``df`` and ``AIC`` values match the per-model oracles.
"""

from __future__ import annotations

import io
import contextlib

import numpy as np
import polars as pl
import pytest

from conftest import load_dataset, load_glm_oracle
from hea import AIC, BIC, Binomial, Gamma, Gaussian, Poisson, anova, glm


# ---------------------------------------------------------------------------
# Build the same nested fits the R oracle script does. Centralizing here so
# each parametrized case reuses one fitter instead of inlining the recipe.
# ---------------------------------------------------------------------------


def _fits_anova_poisson_quine():
    d = load_dataset("MASS", "quine")
    fam = Poisson(link="log")
    return [
        glm("Days ~ Sex + Age", d, family=fam),
        glm("Days ~ Sex + Age + Eth + Lrn", d, family=fam),
    ]


def _fits_anova_gamma_trees():
    d = load_dataset("R", "trees")
    fam = Gamma(link="inverse")
    return [
        glm("Volume ~ log(Girth)", d, family=fam),
        glm("Volume ~ log(Height) + log(Girth)", d, family=fam),
    ]


def _fits_anova_gaussian_iris():
    d = load_dataset("R", "iris")
    fam = Gaussian()
    return [
        glm("Sepal.Length ~ 1", d, family=fam),
        glm("Sepal.Length ~ Petal.Length", d, family=fam),
        glm("Sepal.Length ~ Petal.Length + Species", d, family=fam),
    ]


def _fits_anova_binomial_menarche():
    # Same proportion+weights rewrite test_glm_examples uses for cbind.
    d = load_dataset("MASS", "menarche")
    p = (d["Menarche"] / d["Total"]).rename("p")
    d2 = d.with_columns(p)
    w = d["Total"].to_numpy().astype(float)
    fam = Binomial(link="logit")
    return [
        glm("p ~ 1", d2, family=fam, weights=w),
        glm("p ~ Age", d2, family=fam, weights=w),
    ]


ANOVA_CASES = {
    "anova_poisson_quine":     _fits_anova_poisson_quine,
    "anova_gamma_trees":       _fits_anova_gamma_trees,
    "anova_gaussian_iris":     _fits_anova_gaussian_iris,
    "anova_binomial_menarche": _fits_anova_binomial_menarche,
}


# ---------------------------------------------------------------------------
# anova(glm,...) parity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("oid", list(ANOVA_CASES.keys()))
def test_anova_glm(oid: str):
    o = load_glm_oracle(oid)
    fits = ANOVA_CASES[oid]()

    # Capture stdout so the printed table doesn't pollute pytest output;
    # we verify against the *returned* dataframe.
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        df = anova(*fits)

    assert isinstance(df, pl.DataFrame), f"anova(glm) should return a polars DataFrame; got {type(df)}"

    # Per-row residual df / dev — order should match the oracle (sorted by
    # df_residuals descending, which equals the input order for nested fits).
    np.testing.assert_array_equal(
        np.asarray(df["Resid. Df"].to_numpy()),
        np.asarray(o["resid_df"], dtype=int),
    )
    np.testing.assert_allclose(
        df["Resid. Dev"].to_numpy(),
        np.asarray(o["resid_dev"]),
        atol=5e-3,
    )

    # Incremental columns: Df / Deviance / stat / p — first row is None.
    test = o["test"]
    stat_col = "F" if test == "F" else "Deviance"
    p_col = "Pr(>F)" if test == "F" else "Pr(>Chi)"

    df_hea = df["Df"].to_list()
    dev_hea = df["Deviance"].to_list()
    stat_hea = df[stat_col].to_list()
    p_hea = df[p_col].to_list()
    for i in range(len(o["df"])):
        df_R, dev_R = o["df"][i], o["deviance"][i]
        stat_R, p_R = o["stat"][i], o["pvalue"][i]
        if df_R is None:
            assert df_hea[i] is None and dev_hea[i] is None, \
                f"row {i}: expected None for first row"
            assert stat_hea[i] is None and p_hea[i] is None
            continue
        assert df_hea[i] == df_R, \
            f"row {i}: Df hea={df_hea[i]} R={df_R}"
        np.testing.assert_allclose(dev_hea[i], dev_R, atol=5e-3,
            err_msg=f"row {i}: Deviance hea={dev_hea[i]} R={dev_R}")
        np.testing.assert_allclose(stat_hea[i], stat_R, atol=5e-3,
            err_msg=f"row {i}: {stat_col} hea={stat_hea[i]} R={stat_R}")
        # p-value: meaningful values to 5e-3; tiny values just need to be tiny.
        if p_R > 1e-10:
            np.testing.assert_allclose(p_hea[i], p_R, atol=5e-3,
                err_msg=f"row {i}: {p_col} hea={p_hea[i]} R={p_R}")
        else:
            assert p_hea[i] < 1e-6, \
                f"row {i}: {p_col} hea={p_hea[i]} should be tiny like R={p_R}"


# ---------------------------------------------------------------------------
# AIC()/BIC() smoke — the helpers print and return None; we just confirm
# they don't raise on glm fits and that the per-model values shown agree
# with the per-model oracles already pinned in test_glm_examples.
# ---------------------------------------------------------------------------


def test_aic_bic_dispatch_on_glm():
    fits = _fits_anova_gaussian_iris()
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        AIC(*fits)
        BIC(*fits)
    out = buf.getvalue()
    # Each model's AIC and BIC should appear in the printed table to 2dp,
    # which is the rounding the helpers apply.
    for m in fits:
        assert f"{m.AIC:.2f}" in out, f"AIC table missing {m.AIC:.2f}"
        assert f"{m.BIC:.2f}" in out, f"BIC table missing {m.BIC:.2f}"


def test_anova_rejects_mixed_types():
    from hea import lm
    d = load_dataset("R", "iris")
    m_lm = lm("Sepal.Length ~ Petal.Length", d)
    m_glm = glm("Sepal.Length ~ Petal.Length", d, family=Gaussian())
    with pytest.raises(TypeError, match="same type"):
        anova(m_lm, m_glm)


def test_anova_rejects_mixed_families():
    d = load_dataset("R", "trees")
    m1 = glm("Volume ~ log(Girth)", d, family=Gamma(link="inverse"))
    m2 = glm("Volume ~ log(Girth)", d, family=Gamma(link="log"))
    with pytest.raises(ValueError, match="family and link"):
        anova(m1, m2)


def test_anova_glm_test_argument():
    """`test=` switches the statistic — pinned to R's anova.glm output on
    Wood's heart data (cbind(ha, ok) ~ ck via the proportion + weights form)."""
    import io, contextlib
    import polars as pl
    from hea.family import Binomial
    heart = pl.DataFrame({
        "ck": [20, 60, 100, 140, 180, 220, 260, 300, 340, 380, 420, 460],
        "ha": [2, 13, 30, 30, 21, 19, 18, 13, 19, 15, 7, 8],
        "ok": [88, 26, 8, 5, 0, 1, 1, 1, 1, 0, 0, 0],
    }).with_columns(
        n=pl.col("ha") + pl.col("ok"),
        p=pl.col("ha") / (pl.col("ha") + pl.col("ok")),
    )
    n = heart["n"].to_numpy()
    m0 = glm("p ~ 1",  data=heart, family=Binomial(link="logit"), weights=n)
    m1 = glm("p ~ ck", data=heart, family=Binomial(link="logit"), weights=n)

    # Default + explicit Chisq + LRT alias all give the same table
    for kw in [{}, {"test": "Chisq"}, {"test": "LRT"}, {"test": "lrt"}]:
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            anova(m0, m1, **kw)
        out = buf.getvalue()
        assert "Pr(>Chi)" in out
        assert "234.78" in out  # R's deviance, matches at 2dp

    # test='F' produces an F column
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        anova(m0, m1, test="F")
    out = buf.getvalue()
    assert "Pr(>F)" in out
    assert "234.78" in out

    # test='Rao' is the score test, not implemented yet
    with pytest.raises(NotImplementedError, match="Rao"):
        anova(m0, m1, test="Rao")

    # Bogus value
    with pytest.raises(ValueError, match="must be"):
        anova(m0, m1, test="bogus")


def test_anova_lm_rejects_test_argument():
    """`test=` is glm-only; lm/lme always use F/Chisq respectively."""
    from hea import lm
    d = load_dataset("R", "iris")
    m1 = lm("Sepal.Length ~ Petal.Length", d)
    m2 = lm("Sepal.Length ~ Petal.Length + Petal.Width", d)
    with pytest.raises(TypeError, match="test="):
        anova(m1, m2, test="Chisq")
