"""R-oracle parity tests for ``hea.glm``.

Each test pins ``hea.glm(...)`` outputs against the corresponding
``stats::glm(...)`` JSON oracle generated by ``tests/scripts/make_glm_oracles.R``.
The 11 (family, link, dataset) triples cover the family/link matrix laid
out in ``.claude/plans/glm-port.md`` Phase 0.2.

Tolerances are deliberately tight (5e-5 on coef / dev / dispersion / AIC)
because Fisher-IRLS is essentially deterministic — any drift bigger than
that is a bug, not numerical noise.
"""

from __future__ import annotations

import numpy as np
import pytest

from conftest import load_dataset, load_glm_oracle
from hea import (
    Binomial, Gamma, Gaussian, InverseGaussian, Poisson, glm,
)


# ---------------------------------------------------------------------------
# Per-oracle case construction. Each entry is a dict that knows how to
# rebuild the hea fit corresponding to its R-side oracle. Centralizing this
# keeps the parametrized tests below from each having a custom fitting branch.
# ---------------------------------------------------------------------------


def _build_iris():
    d = load_dataset("R", "iris")
    return glm("Sepal.Length ~ Petal.Length + Species", d, family=Gaussian())


def _build_insurance_gaussian_log():
    d = load_dataset("MASS", "Insurance").filter(load_dataset("MASS", "Insurance")["Claims"] > 0)
    off = np.log(d["Holders"].to_numpy().astype(float))
    return glm("Claims ~ District + Group", d, family=Gaussian(link="log"),
               offset=off)


def _build_trees(link: str):
    d = load_dataset("R", "trees")
    return glm("Volume ~ log(Height) + log(Girth)", d,
               family=Gamma(link=link))


def _build_quine(link: str):
    d = load_dataset("MASS", "quine")
    return glm("Days ~ Sex + Age + Eth + Lrn", d, family=Poisson(link=link))


def _build_menarche(link: str):
    # cbind(Menarche, Total - Menarche) ~ Age. hea's parser doesn't yet
    # accept cbind() on the LHS (Phase 6.1), so we pre-convert to
    # (proportion, weights=Total) which is the algebraically equivalent
    # binomial-with-size form.
    d = load_dataset("MASS", "menarche")
    d2 = d.with_columns([(d["Menarche"] / d["Total"]).alias("p")])
    return glm("p ~ Age", d2, family=Binomial(link=link),
               weights=d["Total"].to_numpy().astype(float))


def _build_ig_insurance():
    d = load_dataset("MASS", "Insurance").filter(load_dataset("MASS", "Insurance")["Claims"] > 0)
    return glm("Claims ~ Group", d, family=InverseGaussian())


CASES = {
    "gaussian_identity_iris":     _build_iris,
    "gaussian_log_insurance":     _build_insurance_gaussian_log,
    "gamma_inverse_trees":        lambda: _build_trees("inverse"),
    "gamma_log_trees":            lambda: _build_trees("log"),
    "poisson_log_quine":          lambda: _build_quine("log"),
    "poisson_sqrt_quine":         lambda: _build_quine("sqrt"),
    "binomial_logit_menarche":    lambda: _build_menarche("logit"),
    "binomial_probit_menarche":   lambda: _build_menarche("probit"),
    "binomial_cauchit_menarche":  lambda: _build_menarche("cauchit"),
    "binomial_cloglog_menarche":  lambda: _build_menarche("cloglog"),
    "ig_canonical_insurance":     _build_ig_insurance,
}

ALL_ORACLES = list(CASES.keys())


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _allclose(actual, expected, *, atol, rtol=0.0, name=""):
    np.testing.assert_allclose(
        actual, expected, atol=atol, rtol=rtol,
        err_msg=f"{name}: hea={actual} R={expected}",
    )


# ---------------------------------------------------------------------------
# Phase 1 — engine + core fit (coef, deviance, fitted/η, residuals, iter).
# Tight tolerances: Fisher IRLS is essentially deterministic.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("oid", ALL_ORACLES)
def test_glm_core_fit(oid: str):
    o = load_glm_oracle(oid)
    m = CASES[oid]()

    assert m.column_names == o["coef_names"]
    assert m.n == o["n"]
    assert m.df_residual == o["df_residual"]
    assert m.converged == o["converged"]
    # IRLS iter count: hea must not blow up vs R, but converging faster is
    # fine — gaussian_log_insurance is the canonical example, where R was
    # given a deliberately poor `start = log(y+1e-3)` to satisfy μ>0 and so
    # needs 11 iters, while hea's default init lands near the optimum and
    # converges in 4. Allow hea ≤ R+2.
    assert m.iter <= o["iter"] + 2, f"iter: hea={m.iter} R={o['iter']}"

    _allclose(m._bhat_arr, np.asarray(o["coefficients"]),
              atol=5e-5, name="coef")
    _allclose(m.deviance, o["deviance"], atol=5e-4, name="deviance")
    _allclose(m.fitted_values, np.asarray(o["fitted_values"]),
              atol=5e-4, name="fitted")
    _allclose(m.linear_predictors, np.asarray(o["linear_pred"]),
              atol=5e-4, name="linear_pred")
    _allclose(m.residuals_of("response"), np.asarray(o["res_response"]),
              atol=5e-4, name="res_response")
    _allclose(m.residuals_of("working"), np.asarray(o["res_working"]),
              atol=5e-4, name="res_working")
    _allclose(m.residuals_of("pearson"), np.asarray(o["res_pearson"]),
              atol=5e-4, name="res_pearson")
    _allclose(m.residuals_of("deviance"), np.asarray(o["res_deviance"]),
              atol=5e-4, name="res_deviance")


# ---------------------------------------------------------------------------
# Phase 2 — Wald inference (vcov, SE, t/z, p, CI). The t-vs-z dispatch is
# scale_known-driven; the column header for the printed summary follows the
# same rule.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("oid", ALL_ORACLES)
def test_glm_inference(oid: str):
    o = load_glm_oracle(oid)
    m = CASES[oid]()

    # vcov
    _allclose(m.vcov, np.asarray(o["vcov"]), atol=5e-6, name="vcov")
    _allclose(m._se_bhat_arr, np.asarray(o["std_error"]),
              atol=5e-5, name="se")

    # t / z statistic — column 3 of summary(m)$coefficients
    expected_kind = o["test_kind"]
    assert m._test_kind == expected_kind, \
        f"test kind: hea={m._test_kind} R={expected_kind}"
    _allclose(m._stat_arr, np.asarray(o["test_stat"]),
              atol=5e-3, name="test_stat")

    # p-values — broaden tol on extreme-tail entries (R uses exact tail
    # math; we use scipy's). Anything > 1e-10 should match to 5e-3 abs.
    p_hea = np.asarray(m.p_values.row(0), dtype=float)
    p_R = np.asarray(o["p_value"])
    mask_meaningful = p_R > 1e-10
    if mask_meaningful.any():
        _allclose(p_hea[mask_meaningful], p_R[mask_meaningful],
                  atol=5e-3, name="p_value(meaningful)")
    # Tiny p-values: just assert hea is also tiny.
    if (~mask_meaningful).any():
        assert np.all(p_hea[~mask_meaningful] < 1e-6), \
            f"p-value(tiny): hea={p_hea} R={p_R}"

    # 95% Wald CI — confint.default convention.
    ci_low = m.ci_bhat[m.ci_bhat.columns[1]].to_numpy()
    ci_hi = m.ci_bhat[m.ci_bhat.columns[2]].to_numpy()
    _allclose(ci_low, np.asarray(o["ci_lower"]), atol=5e-4, name="CI lower")
    _allclose(ci_hi, np.asarray(o["ci_upper"]), atol=5e-4, name="CI upper")

    # dispersion — Pearson estimator; 1.0 for scale-known.
    _allclose(m.dispersion, o["dispersion"], atol=5e-5, name="dispersion")


# ---------------------------------------------------------------------------
# Phase 3 — null deviance, AIC, BIC, logLik. Family/link-aware AIC routes
# through family.aic + 2·rank (R glm convention; the dispersion df is folded
# into family.aic for unknown-scale families).
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("oid", ALL_ORACLES)
def test_glm_aic_bic_loglik(oid: str):
    o = load_glm_oracle(oid)
    m = CASES[oid]()

    _allclose(m.null_deviance, o["null_deviance"], atol=5e-4,
              name="null_deviance")
    assert m.df_null == o["df_null"]
    _allclose(m.aic, o["aic"], atol=5e-3, name="aic")
    _allclose(m.loglike, o["loglik"], atol=5e-3, name="loglik")
    assert m.npar == o["loglik_df"], \
        f"npar (= logLik$df): hea={m.npar} R={o['loglik_df']}"
    _allclose(m.bic, o["bic"], atol=5e-3, name="bic")


# ---------------------------------------------------------------------------
# Phase 4 — predict(type=link/response, se.fit=TRUE). The link-scale SE is
# √diag(X·vcov·Xᵀ); the response-scale SE is |dμ/dη(η̂)|·se_link (delta
# method). predict.glm with no newdata reuses the fit-time offset so η̂
# matches `m$linear.predictors`.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("oid", ALL_ORACLES)
def test_glm_predict(oid: str):
    o = load_glm_oracle(oid)
    m = CASES[oid]()

    # Link scale.
    fit_link, se_link = m.predict(type="link", se_fit=True)
    _allclose(fit_link, np.asarray(o["pred_link_fit"]),
              atol=5e-4, name="pred_link_fit")
    _allclose(se_link, np.asarray(o["pred_link_se"]),
              atol=5e-5, name="pred_link_se")

    # Response scale (delta method on SE). Use rtol on the SE because the
    # delta-method multiplier |dμ/dη| is huge for some links (IG canonical:
    # ~μ³/2 ≈ 1.9e4 on Insurance), which amplifies tiny vcov differences
    # (~1e-7) to ~5e-3 absolute even though relative error stays ~1e-4.
    fit_resp, se_resp = m.predict(type="response", se_fit=True)
    _allclose(fit_resp, np.asarray(o["pred_resp_fit"]),
              atol=5e-4, name="pred_resp_fit")
    _allclose(se_resp, np.asarray(o["pred_resp_se"]),
              atol=5e-5, rtol=5e-4, name="pred_resp_se")

    # Without se_fit, predict returns the bare fit only — same numbers.
    _allclose(m.predict(type="link"), fit_link, atol=0.0, name="link no-se")
    _allclose(m.predict(type="response"), fit_resp, atol=0.0,
              name="response no-se")
